### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by MyAlejo** [christian-fei/free-google-translate-with-puppeteer#2]
![image](https://user-images.githubusercontent.com/66756673/91999055-9512aa00-ed01-11ea-9360-1b86c92f311c.png)

**Comment by christian-fei** [comment]
try installing all libs

```
apt-get update && \ 
     apt-get install -yq --no-install-recommends \ 
     libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \ 
     libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \ 
     libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \ 
     libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \ 
     libnss3 
```

if you're running in docker -> https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker

and generally to solve issues / troubleshooting, refer to https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

**Comment by MyAlejo** [comment]
On my pc everything was working correctly but when I went to the hosting, that error started to appear, I can't run apt on the hosting, most likely it has to do with the machine?

**Comment by christian-fei** [comment]
yep it's most likely related to the packages available on the machine you're using
